import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const profiles = sqliteTable('profiles', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  resumePath: text('resume_path'),
  currentTitle: text('current_title').notNull(),
  totalExperience: real('total_experience').notNull(),
  currentCompany: text('current_company'),
  skills: text('skills').notNull().default('[]'),
  education: text('education').notNull().default('[]'),
  preferredTitles: text('preferred_titles').notNull().default('[]'),
  preferredLocations: text('preferred_locations').notNull().default('[]'),
  keywords: text('keywords').notNull().default('[]'),
  currentCtc: real('current_ctc'),
  expectedCtc: real('expected_ctc'),
  noticePeriod: text('notice_period').notNull().default('immediate'),
  immediateJoiner: integer('immediate_joiner', { mode: 'boolean' }).notNull().default(false),
  willingToRelocate: integer('willing_to_relocate', { mode: 'boolean' }).notNull().default(false),
  preferredWorkMode: text('preferred_work_mode').notNull().default('any'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const jobs = sqliteTable('jobs', {
  id: text('id').primaryKey(),
  externalId: text('external_id').notNull(),
  source: text('source').notNull(),
  title: text('title').notNull(),
  company: text('company').notNull(),
  location: text('location').notNull(),
  workMode: text('work_mode'),
  experienceMin: integer('experience_min'),
  experienceMax: integer('experience_max'),
  salaryMin: integer('salary_min'),
  salaryMax: integer('salary_max'),
  salaryCurrency: text('salary_currency'),
  description: text('description'),
  requirements: text('requirements'),
  skills: text('skills'),
  jobUrl: text('job_url').notNull(),
  applyUrl: text('apply_url'),
  postedDate: text('posted_date'),
  scrapedAt: text('scraped_at').notNull(),
  matchScore: integer('match_score'),
  matchedKeywords: text('matched_keywords'),
});

export const applications = sqliteTable('applications', {
  id: text('id').primaryKey(),
  jobId: text('job_id').notNull().references(() => jobs.id),
  status: text('status').notNull().default('queued'),
  appliedAt: text('applied_at'),
  screeningQuestions: text('screening_questions'),
  answersProvided: text('answers_provided'),
  attempts: integer('attempts').notNull().default(0),
  lastAttemptAt: text('last_attempt_at'),
  error: text('error'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const settings = sqliteTable('settings', {
  id: text('id').primaryKey().default('default'),
  llmBaseUrl: text('llm_base_url').notNull().default('http://localhost:1234'),
  llmModel: text('llm_model'),
  llmTemperature: real('llm_temperature').notNull().default(0.7),
  llmMaxTokens: integer('llm_max_tokens').notNull().default(1024),
  automationDelay: integer('automation_delay').notNull().default(5000),
  automationMaxPerSession: integer('automation_max_per_session').notNull().default(50),
  automationHeadless: integer('automation_headless', { mode: 'boolean' }).notNull().default(false),
  automationRetry: integer('automation_retry', { mode: 'boolean' }).notNull().default(true),
  automationMaxRetries: integer('automation_max_retries').notNull().default(3),
  credentials: text('credentials'),
  notificationsSound: integer('notifications_sound', { mode: 'boolean' }).notNull().default(true),
  notificationsDesktop: integer('notifications_desktop', { mode: 'boolean' }).notNull().default(true),
  updatedAt: text('updated_at').notNull(),
});

export const applicationLogs = sqliteTable('application_logs', {
  id: text('id').primaryKey(),
  applicationId: text('application_id').notNull().references(() => applications.id),
  timestamp: text('timestamp').notNull(),
  level: text('level').notNull(),
  message: text('message').notNull(),
  details: text('details'),
});
